### ISSUE TITLE
Добавить состояния игры

### ISSUE THREAD

**Issue by UhBroSeemOff** [UhBroSeemOff/space-jump#1]
Подразумевается добавление двух типов состояний: **макросостояние игры** (главное меню, уровень) и **микросостояние систем** (до опроса/опрос/после опроса)

Первое состояние является очевидным разграничителем, второе - позволяет избежать множества багов, связанных с инициализацией и использованием каких-либо систем (например, это фиксит проблему, когда в одном тике создается игрок и вызывается система, которой критично наличие игрока на сцене)

**Comment by descrybe** [comment]
Создал ветку для меню и initial ui: initial-ui.
Туда положил ApplicationState
